#cloud-config

write_files:
  - path: /etc/ssl/certs/ca-cert.pem
    encoding: base64
    content: |
      ${ca_cert}

coreos:
  update:
    reboot-strategy: etcd-lock

  etcd2:
    name: etcd${count_index}
    discovery-srv: ${cluster_id}.${env}.${dns_zone_name}
    initial-cluster-token: ${env}-${cluster_id}
    advertise-client-urls: http://etcd${count_index}.${cluster_id}.${env}.${dns_zone_name}:2379
    initial-advertise-peer-urls: http://etcd${count_index}.${cluster_id}.${env}.${dns_zone_name}:2380
    listen-client-urls: http://etcd${count_index}.${cluster_id}.${env}.${dns_zone_name}:2379
    listen-peer-urls: http://etcd${count_index}.${cluster_id}.${env}.${dns_zone_name}:2380

  fleet:
    etcd_servers: "http://etcd${count_index}.${cluster_id}.${env}.${dns_zone_name}:2379"
    metadata: "region=${region}"

  units:
    - name: update-ca-certificates.service
      command: start
      content: |
        [Unit]
        Description=Updateds CA certificates
        [Service]
        Type=oneshot
        ExecStart=/usr/sbin/update-ca-certificates
        [Install]
        WantedBy=multi-user.target
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
